name: Build Docker image

on:
  workflow_dispatch:
    inputs:
      RUBY_VERSION:
        description: The version of Ruby to be build
        required: true
        default: master
      UBUNTU_VERSION:
        description: The version of Ubuntu as the base image
        required: true
        default: jammy
      ARCH:
        description: Which architecture amd64 or arm64 do you want to build? (The default is amd64)
        required: false
        default: amd64

jobs:
  build:
    name: ${{ github.event.inputs.RUBY_VERSION }}-${{ github.event.inputs.UBUNTU_VERSION }}-${{ github.event.inputs.ARCH }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          rake docker:build arch=${{ github.event.inputs.arch }} ruby_version=${{ github.event.inputs.RUBY_VERSION }} ubuntu_version=${{ github.event.inputs.UBUNTU_VERSION }}

      - name: Check image
        run: |
          docker images
          docker run rubylang/ruby:${{ github.event.inputs.RUBY_VERSION }}-${{ github.event.inputs.UBUNTU_VERSION }} ruby -v

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push images to DockerHub
        run: docker push rubylang/ruby --all-tags

      - name: Renaming images
        run: |
          docker images rubylang/ruby --format='docker tag {{.Repository}}:{{.Tag}} ghcr.io/ruby/ruby:{{.Tag}}' | sh -ex

      - name: Login GitHub Container Registry
        run: |
          GHCR_TOKEN=${{ secrets.GHCR_TOKEN }}
          echo $GHCR_TOKEN | docker login ghcr.io -u owner --password-stdin

      - name: Push image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/ruby --all-tags
